version: '3'

services: 
  caddy_sever:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy

    ports:
      - "80:80"
      - "443:443"
    networks:
      - mate
  jaus:
    image: kenpusney/jaus:demo
    volumes:
      - ./data:/data
    networks:
      - mate

networks:
  mate:
    external: true
